@isTest
private class TestAccount_MG_AnniversaryDateBatch {
    
    /*
     private static testMethod void BatchTest()
     {
         //insert account
         Account acc_master_b = new Account();
         acc_master_b = USAbleUtility.CreateMasterGroupAccount(); //account returned from utility class
         acc_master_b.Group_Anniversary_Date__c = system.TODAY();
         insert acc_master_b;
         
         test.startTest();
         Account_MG_AnniversaryDateBatch Bat = new Account_MG_AnniversaryDateBatch();
         database.executeBatch(Bat);
         test.stopTest();
         
     }
    private static testMethod void SchdTest()
    {
        test.startTest();
        system.schedule('Schd_Account_Anniv_Date', '0 30 10 1/1 * ? *', new Schd_Account_MG_AnniversaryDateBatch());
        test.stopTest();
    }
    */

}